//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace okimu_discordPort.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("okimu_discordPort.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pref-groups.json.
        /// </summary>
        internal static string CONFIG_GUILD {
            get {
                return ResourceManager.GetString("CONFIG_GUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pref-users.json.
        /// </summary>
        internal static string CONFIG_USER {
            get {
                return ResourceManager.GetString("CONFIG_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this as a command index.
        /// </summary>
        internal static string DESC_HELP {
            get {
                return ResourceManager.GetString("DESC_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      okimu couldn&apos;t find a Cytoid ID to complete your query...\n
        ///      Use &quot;/cytoid bind `id`&quot; to set your Cytoid ID..
        /// </summary>
        internal static string ERR_CYTOID_NO_ID {
            get {
                return ResourceManager.GetString("ERR_CYTOID_NO_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re already in another room!.
        /// </summary>
        internal static string ERR_MATCH_ALREADY_IN_ROOM {
            get {
                return ResourceManager.GetString("ERR_MATCH_ALREADY_IN_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This room is already full!.
        /// </summary>
        internal static string ERR_MATCH_ROOM_FULL {
            get {
                return ResourceManager.GetString("ERR_MATCH_ROOM_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned no results! :(.
        /// </summary>
        internal static string ERR_QUERY_NO_RESULTS {
            get {
                return ResourceManager.GetString("ERR_QUERY_NO_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but you might need to wait a while before you&apos;re unrestricted / unbanned!.
        /// </summary>
        internal static string ERR_USER_BANNED {
            get {
                return ResourceManager.GetString("ERR_USER_BANNED", resourceCulture);
            }
        }
    }
}
